import os


DIALECT='mysql'
DRIVER='mysqldb'
USERNAME='root'
PASSWORD='147258369gkjy'
HOST='127.0.0.1'
PORT='3306'
DATABASE='demo'


SQLALCHEMY_DATABASE_URI =  "{}+{}://{}:{}@{}:{}/{}?charset=utf8".format(DIALECT, DRIVER, USERNAME, PASSWORD, HOST, PORT, DATABASE)


SQLALCHEMY_TRACK_MODIFICATIONS = False


DEBUG = True


